//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDetails.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAddress
    {
        public long Id { get; set; }
        public System.Guid EmployeeId { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Pincode { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
